# Generated by Django 5.2.2 on 2025-06-09 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('combate', 'Combate'), ('poomsae', 'Poomsae'), ('departamental', 'Departamental'), ('ranking', 'Ranking'), ('nacional', 'Nacional')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gimnasio', models.CharField(max_length=100)),
                ('cui', models.CharField(max_length=20, unique=True, verbose_name='DPI o CUI del Entrenador')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('cui', models.CharField(max_length=20, unique=True, verbose_name='CUI o Pasaporte')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('cinta', models.CharField(choices=[('blanca', 'Blanca'), ('amarilla', 'Amarilla'), ('verde', 'Verde'), ('azul', 'Azul'), ('roja', 'Roja'), ('negra', 'Negra')], max_length=10)),
                ('categoria', models.CharField(choices=[('cadete', 'Cadete'), ('juvenil', 'Juvenil'), ('adulto', 'Adulto')], max_length=10)),
                ('peso', models.CharField(max_length=10)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('posicion', models.PositiveIntegerField()),
                ('categoria_g', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G4', 'G4')], default='G1', max_length=5)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.atleta')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.atleta')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.CharField(default='Primera ronda', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('atleta_azul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates_azul', to='gestion.atleta')),
                ('atleta_rojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates_rojo', to='gestion.atleta')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combates_ganados', to='gestion.atleta')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.torneo')),
            ],
        ),
    ]
