# Generated by Django 5.2.2 on 2025-06-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='categoria_poomsae',
            field=models.CharField(blank=True, choices=[('tradicional', 'Tradicional'), ('freestyle', 'Freestyle'), ('ambas', 'Ambas')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='disciplina',
            field=models.CharField(choices=[('combate', 'Combate'), ('poomsae', 'Poomsae')], default='combate', max_length=10),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('cadete', 'Cadete'), ('juvenil', 'Juvenil'), ('adulto', 'Adulto')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='peso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
