# Generated by Django 5.2.2 on 2025-06-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_atleta_categoria_poomsae_atleta_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='puntos_ranking',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
